let visit : string[]=["Makka","Disney world","Silcon Vally","London","Tokeyo"]
console.log("Orignal Order")
console.log(visit)
console.log("Sorted array")
console.log([...visit].sort())
console.log(visit)
console.log([...visit].reverse())
console.log(visit)
visit.reverse()
console.log(visit)
visit.reverse()
console.log(visit)
visit.sort()
console.log(visit)
visit.sort().reverse()
console.log(visit)